services:
  catalogdb:
    image: postgres:18
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Catalogdb
    ports:
      - "5432:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

volumes:
  pgdata:

